version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: minequiz-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ttf
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: minequizdb
    volumes:
      - mongo_data:/data/db
    networks:
      - minequiz-net

volumes:
  mongo_data:

networks:
  minequiz-net:
    driver: bridge